// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQF4Xf271NjNxxt2M-snlUgOn2eLgn-2w',
    appId: '1:477546719510:web:61352fd6b28ac505ea8837',
    messagingSenderId: '477546719510',
    projectId: 'holbegram-2506',
    authDomain: 'holbegram-2506.firebaseapp.com',
    storageBucket: 'holbegram-2506.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2MQvvKIXgSA409Z1KiIsyCdR3LCfjxr0',
    appId: '1:477546719510:android:80e33c4fd66d2bf1ea8837',
    messagingSenderId: '477546719510',
    projectId: 'holbegram-2506',
    storageBucket: 'holbegram-2506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnoPmqp8NxkUtHh80aKiL4qL2q5th_Co',
    appId: '1:477546719510:ios:7ee9bd41685862ceea8837',
    messagingSenderId: '477546719510',
    projectId: 'holbegram-2506',
    storageBucket: 'holbegram-2506.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnoPmqp8NxkUtHh80aKiL4qL2q5th_Co',
    appId: '1:477546719510:ios:7ee9bd41685862ceea8837',
    messagingSenderId: '477546719510',
    projectId: 'holbegram-2506',
    storageBucket: 'holbegram-2506.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQF4Xf271NjNxxt2M-snlUgOn2eLgn-2w',
    appId: '1:477546719510:web:e1a7d11b01b893d5ea8837',
    messagingSenderId: '477546719510',
    projectId: 'holbegram-2506',
    authDomain: 'holbegram-2506.firebaseapp.com',
    storageBucket: 'holbegram-2506.firebasestorage.app',
  );
}
